# DevOps pipeline for CLGuild01 deployment

parameters:
- name: branchName
  displayName: 'Branch to build/deploy'
  type: string
  default: 'master'
- name: branchName2
  displayName: 'Branch to build/deploy 2'
  type: string
  default: 'master'
- name: azureSubscription
  displayName: 'Azure subscription name'
  type: string
  # default: 'PYueh-Visual Studio Enterprise Subscription(94e67d6d-a3e6-425f-b9af-16971682c94c)'
- name: storageAccount
  displayName: 'Storage account resource name'
  type: string
  # default: 'petersandbox1'
- name: deployPath
  displayName: 'Deploy path (https://x.com/<dir/../dir>)'
  type: string
  # default: 'ja/Countries'

jobs:
  - job: Deploy_To_Azure
    dependsOn: Build_DocFx
    pool:
      vmImage: 'vs2017-win2016'
      # name: CLGuild
    steps:
      - script: |
          echo "script: Executing job Deploy_To_Azure"
          echo "azureSubscription = %azureSubscription%"
          echo "storageAccount = %storageAccount%"
          echo "deployPath = %deployPath%"
          echo "Artifacts = %System_ArtifactsDirectory"

      - powershell: |
          Write-Output "powershell: Executing job Deploy_To_Azure"
          Write-Output "azureSubscription = ${{parameters.azureSubscription}}"
          Write-Output "storageAccount = ${{parameters.storageAccount}}"
          Write-Output "deployPath = ${{parameters.deployPath}}"
          Write-Output "deployPath = $env:deployPath"
          Write-Output "System.ArtifactsDirectory = $env:System_ArtifactsDirectory"

      - task: DownloadBuildArtifacts@0
        inputs:
          buildType: 'current'
          downloadType: 'single'
          artifactName: 'drop'
          downloadPath: '$(System.ArtifactsDirectory)'

      - task: AzureCLI@2
        inputs:
          azureSubscription: ${{parameters.azureSubscription}}
          scriptType: 'ps'
          scriptLocation: 'inlineScript'
          inlineScript: 'az storage blob delete-batch --source "`$web" --account-name "${{parameters.storageAccount}}" --pattern "${{parameters.deployPath}}/*"'

      - task: AzureFileCopy@4
        inputs:
          SourcePath: '$(System.ArtifactsDirectory)\drop\**'
          # SourcePath: '$(Build.ArtifactStagingDirectory)\drop\**'
          # SourcePath: 'C:\source\Edgecmd-Docs\_site\**'
          azureSubscription: ${{parameters.azureSubscription}}
          Destination: 'AzureBlob'
          storage: ${{parameters.storageAccount}}
          ContainerName: '$web'
          BlobPrefix: 'ja/Countries'

