# DevOps pipeline for Azure cloud deployment

trigger: none
#  batch: false
#  branches:
#    include:
#      - master

variables:
  - group: product-readiness.docfx
  - name: gitRepoName
    value: Countries.ja
  - name: gitOwner
    value: pyueh-osi
  - name: contentLanguage
    value: ja

jobs:
  - job: Publish
    pool:
      # name: 00-OSIManaged-Containers
      # demands: AgentType -equals osimanagedagent
      vmImage: 'vs2017-win2016'
    steps:
      - script: |
          choco install DocFX --version=2.56.2
        displayName: 'Install DocFX 2.56.2'
      - script: |
          choco install wkhtmltopdf --version=0.12.5
        displayName: 'Install wkhtmltopdf 0.12.5'

      - script: |
          echo.
          dir
          echo.
          echo.
          echo "*** Clone source ***"
          echo.
          mkdir source
          cd source
          git clone -b master https://user:$(gitToken)@github.com/$(gitOwner)/$(gitRepoName).git --recurse-submodules
          dir
          cd $(gitRepoName)\docfx_project
          dir
          echo.
          echo "*** Build DocFx site ***"
          echo.
          docfx.exe build ./docfx.json
          echo.
          echo "*** Build PDF ***"
          echo.
          docfx.exe pdf ./docfx.json
          copy _site_pdf\*.pdf _site
          echo.
          echo "*** Contents of _site ***"
          echo.
          dir "C:\source\$(gitRepoName)\docfx_project\_site"
          echo.
          echo "Complete"
          echo.
        workingDirectory: 'C:\'
        displayName: 'Publish DocFX'

      - powershell: |

            Write-Output "env:Build_SourcesDirectory = $env:Build_SourcesDirectory"
            Write-Output "gitRepoName = $env:gitRepoName"
                    
##          set-variable -name "src_dir" -value "$env:Build_SourcesDirectory\$gitRepoName"
##          set-variable -name "build_info_file" -value "$src_dir\docfx_project\_site\BuildInfo.txt"
##          new-item -path $build_info_file -itemtype file
##          
##          add-content -path $build_info_file -value "Build Time      : $build_timestamp"
##          add-content -path $build_info_file -value "Source Repo     : $env:Build_Repository_Uri"
##          add-content -path $build_info_file -value "Branch          : $env:Build_SourceBranchName"
##          add-content -path $build_info_file -value "Last Commit     : $env:Build_SourceVersion"
##          add-content -path $build_info_file -value ""
##          add-content -path $build_info_file -value "Other Build Info:"
##          add-content -path $build_info_file -value "- Agent         : $env:Agent_MachineName"
##          add-content -path $build_info_file -value "- Name          : $env:Build_DefinitionName"
##          add-content -path $build_info_file -value "- Number        : $env:Build_BuildNumber"
##          add-content -path $build_info_file -value "- Reason        : $env:Build_Reason"
##          add-content -path $build_info_file -value "- Requested For : $env:Build_RequestedFor"
##          add-content -path $build_info_file -value "- Queued By     : $env:Build_QueuedBy"
##
        displayName: 'Write BuildInfo.txt file'


      - task: PublishBuildArtifacts@1
        inputs:
          PathtoPublish: 'C:\source\$(gitRepoName)\docfx_project\_site'
          ArtifactName: 'drop'
          publishLocation: 'Container'

      - task: AzureCLI@2
        displayName: 'Clean web server deployment directory'
        inputs:
          azureSubscription: 'PYueh-Visual Studio Enterprise Subscription(94e67d6d-a3e6-425f-b9af-16971682c94c)'
          scriptType: 'ps'
          scriptLocation: 'inlineScript'
          inlineScript: 'az storage blob delete-batch --source "`$web" --account-name "petersandbox1" --pattern "de/Countries/*"'

      - task: AzureFileCopy@4
        displayName: 'Deploy to web server'
        inputs:
          # SourcePath: '$(Build.ArtifactStagingDirectory)'
          SourcePath: 'C:\source\$(gitRepoName)\docfx_project\_site\**'
          azureSubscription: 'PYueh-Visual Studio Enterprise Subscription(94e67d6d-a3e6-425f-b9af-16971682c94c)'
          Destination: 'AzureBlob'
          storage: 'petersandbox1'
          ContainerName: '$web'
          BlobPrefix: 'ja/Countries'
